[package]
name = "cardputer-hello"
version = "0.1.0"
authors = ["Denis Beresnev"]
edition = "2021"
resolver = "2"
rust-version = "1.77"

[[bin]]
name = "cardputer-hello"
harness = false

[profile.release]
opt-level = "s"

[profile.dev]
debug = true
opt-level = "z"

[features]
default = ["std", "esp-idf-svc/native"]

pio = ["esp-idf-svc/pio"]
std = ["alloc", "esp-idf-svc/binstart", "esp-idf-svc/std"]
alloc = ["esp-idf-svc/alloc"]
nightly = ["esp-idf-svc/nightly"]
experimental = ["esp-idf-svc/experimental"]

[dependencies]
log = "0.4"
esp-idf-svc = "0.51"

shared = { path = "../../shared" }

[build-dependencies]
embuild = "0.33"
